name: Deploy Multiliangual Site

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/setup-pages@v2

      - name: Build and Deploy
        run: |
          echo "Building and deploying website..."
          # Создаем директорию для релиза
          mkdir -p gh-pages/v${{ github.event.release.name }}
          # Копируем файлы для каждой языковой версии
          cp -r v1/ru gh-pages/v${{ github.event.release.name }}/ru
          cp -r v2/en gh-pages/v${{ github.event.release.name }}/en
          # Копируем файл index.html
          cp index.html gh-pages/v${{ github.event.release.name }}
          # Добавляем все файлы в Git
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Deploy version ${{ github.event.release.name }}"
          git push origin gh-pages
